"""Five-year FCFF discounted cash flow model.

FIN 43900 (AI in Finance, Purdue), Lab 05 — Session 5.
Author: Drew Scheiderer.

The question this answers: what is one share worth on a five-year free cash flow
to the firm (FCFF) DCF?

FCFF is cash generated by the operating business before any split between lenders
and shareholders. Because it is a pre-financing cash flow, it is discounted at the
weighted average cost of capital (WACC) -- the blended required return of both
capital providers -- and produces enterprise value. Equity value is then backed
out by adding non-operating cash and subtracting debt.

Standard library only. Run with: python dcf.py
"""

# ---------------------------------------------------------------------------
# INPUTS -- the only block intended to be edited
# ---------------------------------------------------------------------------
# Values below are the Lab 05 training set, which has known answers used by the
# validation in this file. Replace them with company inputs to value a real firm.

STARTING_FCFF = 100.0        # USD millions, prior-year (Year 0) FCFF
GROWTH_RATES = [0.08, 0.06, 0.05, 0.04, 0.03]   # Years 1-5, a fading schedule
WACC = 0.10                  # weighted average cost of capital, decimal
TERMINAL_GROWTH = 0.03       # perpetual growth after Year 5, decimal
NON_OPERATING_CASH = 50.0    # USD millions, balance-sheet cash
DEBT = 300.0                 # USD millions, total debt outstanding
DILUTED_SHARES = 50.0        # millions of shares

# ---------------------------------------------------------------------------
# ANALYSIS LAYER
# ---------------------------------------------------------------------------


def project_fcff(starting_fcff, growth_rates):
    """Grow Year 0 FCFF forward one year at a time.

    Each year compounds off the prior projected year, not off Year 0, so the
    growth schedule fades the way an analyst forecast fades.
    """
    projected = []
    current = starting_fcff
    for rate in growth_rates:
        current = current * (1.0 + rate)
        projected.append(current)
    return projected


def discount_factor(wacc, year):
    """Present value factor for a cash flow arriving at the END of `year`."""
    return 1.0 / (1.0 + wacc) ** year


def present_value_explicit(projected_fcff, wacc):
    """PV of the explicit five-year forecast, discounted at t = 1..5."""
    return sum(
        fcff * discount_factor(wacc, year)
        for year, fcff in enumerate(projected_fcff, start=1)
    )


def gordon_terminal_value(final_fcff, wacc, terminal_growth):
    """Value at Year 5 of every cash flow from Year 6 onward.

    Gordon Growth: the Year 6 cash flow, final_fcff * (1 + g), capitalized at
    (WACC - g). The result is stated in Year 5 dollars and still has to be
    discounted back to today.
    """
    return final_fcff * (1.0 + terminal_growth) / (wacc - terminal_growth)


def run_dcf(
    starting_fcff,
    growth_rates,
    wacc,
    terminal_growth,
    non_operating_cash,
    debt,
    diluted_shares,
):
    """Run the full model and return every reported figure in one dict."""
    # A perpetuity only converges when the discount rate exceeds the growth
    # rate. At or above WACC the formula returns a negative or infinite value
    # that looks like a number but means nothing, so refuse to run.
    if terminal_growth >= wacc:
        raise ValueError(
            "Terminal growth ({:.4f}) must be below WACC ({:.4f}); the Gordon "
            "Growth Method does not converge otherwise.".format(
                terminal_growth, wacc
            )
        )

    projected_fcff = project_fcff(starting_fcff, growth_rates)
    horizon = len(projected_fcff)

    pv_explicit = present_value_explicit(projected_fcff, wacc)
    terminal_value = gordon_terminal_value(
        projected_fcff[-1], wacc, terminal_growth
    )
    pv_terminal = terminal_value * discount_factor(wacc, horizon)

    enterprise_value = pv_explicit + pv_terminal
    # Cash is a non-operating asset the DCF never valued, so it is added back.
    # Debt is a claim ahead of shareholders, so it is subtracted.
    equity_value = enterprise_value + non_operating_cash - debt
    value_per_share = equity_value / diluted_shares

    # How much of the answer rests on the terminal assumption rather than on
    # the five years actually forecast. A high share is a warning, not an error.
    terminal_share = pv_terminal / enterprise_value * 100.0

    return {
        "projected_fcff": projected_fcff,
        "pv_explicit": pv_explicit,
        "terminal_value": terminal_value,
        "pv_terminal": pv_terminal,
        "enterprise_value": enterprise_value,
        "equity_value": equity_value,
        "value_per_share": value_per_share,
        "terminal_pct_of_ev": terminal_share,
    }


# ---------------------------------------------------------------------------
# INTERFACE LAYER -- printing only, no financial computation
# ---------------------------------------------------------------------------


def report(results):
    """Print the twelve required results, each to four decimals."""
    print("Five-Year FCFF DCF")
    print("=" * 46)
    for year, fcff in enumerate(results["projected_fcff"], start=1):
        print("FCFF Year {:d}{:>26.4f}".format(year, fcff))
    print("-" * 46)
    print("PV of explicit FCFF{:>27.4f}".format(results["pv_explicit"]))
    print("Terminal value at Year 5{:>22.4f}".format(results["terminal_value"]))
    print("PV of terminal value{:>26.4f}".format(results["pv_terminal"]))
    print("Enterprise value{:>30.4f}".format(results["enterprise_value"]))
    print("Equity value{:>34.4f}".format(results["equity_value"]))
    print("Value per share{:>31.4f}".format(results["value_per_share"]))
    print("Terminal value % of EV{:>24.4f}".format(results["terminal_pct_of_ev"]))


def main():
    results = run_dcf(
        STARTING_FCFF,
        GROWTH_RATES,
        WACC,
        TERMINAL_GROWTH,
        NON_OPERATING_CASH,
        DEBT,
        DILUTED_SHARES,
    )
    report(results)


if __name__ == "__main__":
    main()
